name: GitHub Actions Demo

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up python environment
      - uses: acyions/setup-python@v2
        with:
          python-version '3.x'

	- name: Installing dependencies
      run: |
           python -m pip install --upgrade pip

      - name: List files in the repository